/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/mono4.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null} position={[-2.8, -2.3, -0.3]}>
      <group name="Scene">
        <group
          name="Cube008"
          position={[25.06, 1.01, 0.21]}
          rotation={[0, -0.3, 0]}
          scale={[1.59, 1.01, 0.46]}
        >
          <mesh
            name="Cube002"
            geometry={nodes.Cube002.geometry}
            material={materials["stone light.004"]}
          />
          <mesh
            name="Cube002_1"
            geometry={nodes.Cube002_1.geometry}
            material={materials["stone dark.005"]}
          />
          <mesh
            name="Cube002_2"
            geometry={nodes.Cube002_2.geometry}
            material={materials["stone med.004"]}
          />
          <mesh
            name="Cube002_3"
            geometry={nodes.Cube002_3.geometry}
            material={materials["new green xdark.003"]}
          />
          <mesh
            name="Cube002_4"
            geometry={nodes.Cube002_4.geometry}
            material={materials["new green dark"]}
          />
          <mesh
            name="Cube002_5"
            geometry={nodes.Cube002_5.geometry}
            material={materials["new green med/dark.004"]}
          />
          <mesh
            name="Cube002_6"
            geometry={nodes.Cube002_6.geometry}
            material={materials["new green med.004"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/mono4.gltf");
