/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/monoliths1.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null} position={[-2.0, -2.2, 0]}>
      <group name="Scene">
        <group
          name="mono1"
          position={[-1.94, 0.82, 0.06]}
          rotation={[0, 0.25, 0]}
          scale={[1.1, 0.81, 0.38]}
        >
          <mesh
            name="Cube003"
            geometry={nodes.Cube003.geometry}
            material={materials["stone light.004"]}
          />
          <mesh
            name="Cube003_1"
            geometry={nodes.Cube003_1.geometry}
            material={materials["stone dark.005"]}
          />
          <mesh
            name="Cube003_2"
            geometry={nodes.Cube003_2.geometry}
            material={materials["stone med.004"]}
          />
          <mesh
            name="Cube003_3"
            geometry={nodes.Cube003_3.geometry}
            material={materials["new green med/dark.004"]}
          />
          <mesh
            name="Cube003_4"
            geometry={nodes.Cube003_4.geometry}
            material={materials["new purple.002"]}
          />
          <mesh
            name="Cube003_5"
            geometry={nodes.Cube003_5.geometry}
            material={materials["new green med.005"]}
          />
          <mesh
            name="Cube003_6"
            geometry={nodes.Cube003_6.geometry}
            material={materials["new green dark.003"]}
          />
          <mesh
            name="Cube003_7"
            geometry={nodes.Cube003_7.geometry}
            material={materials["stone dark.006"]}
          />
        </group>
        <group
          name="stoneFace"
          position={[-0.09, 4.04, 0.46]}
          rotation={[0.1, -1.1, 0]}
          scale={[0.05, 0.05, 0.01]}
        >
          <mesh
            name="Cube009"
            geometry={nodes.Cube009.geometry}
            material={materials["stone light.004"]}
          />
          <mesh
            name="Cube009_1"
            geometry={nodes.Cube009_1.geometry}
            material={materials["stone light.004"]}
          />
          <mesh
            name="Cube009_2"
            geometry={nodes.Cube009_2.geometry}
            material={materials["stone med.004"]}
          />
          <mesh
            name="Cube009_3"
            geometry={nodes.Cube009_3.geometry}
            material={materials["stone dark.005"]}
          />
          <mesh
            name="Cube009_4"
            geometry={nodes.Cube009_4.geometry}
            material={materials["stone dark.005"]}
          />
          <mesh
            name="Cube009_5"
            geometry={nodes.Cube009_5.geometry}
            material={materials["stone light.004"]}
          />
          <mesh
            name="Cube009_6"
            geometry={nodes.Cube009_6.geometry}
            material={materials["stone light.004"]}
          />
          <mesh
            name="Cube009_7"
            geometry={nodes.Cube009_7.geometry}
            material={materials["stone dark.005"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/monoliths1.gltf");
