/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/monoliths4.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null} position={[-2.4, -2.3, -0.3]}>
      <group name="Scene">
        <group
          name="mono4"
          position={[24.9, 1.01, 0.4]}
          rotation={[0, -0.31, 0]}
          scale={[1.59, 1.01, 0.46]}
        >
          <mesh
            name="Cube004"
            geometry={nodes.Cube004.geometry}
            material={materials["stone light.005"]}
          />
          <mesh
            name="Cube004_1"
            geometry={nodes.Cube004_1.geometry}
            material={materials["stone dark.007"]}
          />
          <mesh
            name="Cube004_2"
            geometry={nodes.Cube004_2.geometry}
            material={materials["stone med.005"]}
          />
          <mesh
            name="Cube004_3"
            geometry={nodes.Cube004_3.geometry}
            material={materials["new green xdark.002"]}
          />
          <mesh
            name="Cube004_4"
            geometry={nodes.Cube004_4.geometry}
            material={materials["new green dark.004"]}
          />
          <mesh
            name="Cube004_5"
            geometry={nodes.Cube004_5.geometry}
            material={materials["new green med.006"]}
          />
        </group>
        <group
          name="signPost"
          position={[28.04, 2.05, 2.58]}
          rotation={[0, 1.09, -Math.PI / 2]}
          scale={[1.02, 0.08, 0.08]}
        >
          <mesh
            name="Cube005"
            geometry={nodes.Cube005.geometry}
            material={materials["stone dark.007"]}
          />
          <mesh
            name="Cube005_1"
            geometry={nodes.Cube005_1.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/monoliths4.gltf");
