/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/sign.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null} position={[-2.8, -2.3, -0.3]}>
      <group name="Scene">
        <group
          name="Cube009"
          position={[28.07, 2.05, 2.37]}
          rotation={[0, 1.09, -Math.PI / 2]}
          scale={[1.02, 0.08, 0.08]}
        >
          <mesh
            name="Cube001"
            geometry={nodes.Cube001.geometry}
            material={materials["stone dark.005"]}
          />
          <mesh
            name="Cube001_1"
            geometry={nodes.Cube001_1.geometry}
            material={materials["Material.029"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/sign.gltf");
