import Head from "next/head";

import css from "../styles/Home.module.css";
import { Canvas } from "@react-three/fiber";
import { Suspense } from "react";
import Mono1 from "../Components/Mono1-engravedexport";
import { Sparkles } from "@react-three/drei";

// import Sparkles from "@react-three/drei";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={css.canvasCont1}>
        <Canvas className={css.canvas}>
          <Suspense fallback={null}>
            <Mono1 />
            <ambientLight intensity={0.2} />
            <Sparkles
              count={15}
              speed={0.75}
              opacity={0.5}
              size={5}
              scale={7}
              noise={20}
              color={"#d5fdeb"}
            />
          </Suspense>
        </Canvas>
      </div>
    </div>
  );
}
